/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_prituladima_BigFileSorter */

#ifndef _Included_com_prituladima_BigFileSorter
#define _Included_com_prituladima_BigFileSorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_prituladima_BigFileSorter
 * Method:    merge0
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_prituladima_BigFileSorter_merge0
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
